### ISSUE TITLE
Error after posting JSON data

### ISSUE THREAD

**Issue by mauricioabreu** [sdogruyol/spec-kemal#8]
I am using this cool library to test my routes. But I am facing this problem:

```
2016-12-17 10:20:02 -0200 200 GET /todos 79.6µs
.Exception: Missing hash key: HTTP::Headers::Key(@name="host") (KeyError)
0x4b0777: *CallStack::unwind:Array(Pointer(Void)) at ??
0x4b070a: *CallStack#initialize:Array(Pointer(Void)) at ??
0x4b06da: *CallStack::new:CallStack at ??
0x4a601e: *raise<KeyError>:NoReturn at ??
0x53f14f: *Hash(HTTP::Headers::Key, Array(String)) at ??
0x53dc32: *HTTP::Headers#fetch<HTTP::Headers::Key>:String at ??
0x53dbdd: *HTTP::Headers#[]<String>:String at ??
0x4a99cb: *base_url<HTTP::Server::Context>:String at ??
0x4aa299: ~procProc(HTTP::Server::Context, String) at ??
0x4a95ef: ~proc3Proc(HTTP::Server::Context, String) at ??
0x593376: *Kemal::RouteHandler#process_request<HTTP::Server::Context>:HTTP::Server::Context at ??
0x5932e6: *Kemal::RouteHandler#call<HTTP::Server::Context>:HTTP::Server::Context at ??
0x588ea1: *Kemal::FilterHandler at ??
0x588cba: *Kemal::FilterHandler#call<HTTP::Server::Context>:(Array(IO) | Bool | HTTP::Server::Context | HTTP::Server::Response | HTTP::Server::Response::Output | IO::FileDescriptor+ | Int32 | Nil) at ??
0x592372: *Kemal::StaticFileHandler at ??
0x591435: *Kemal::StaticFileHandler#call<HTTP::Server::Context>:(Array(IO) | Bool | HTTP::Server::Context | HTTP::Server::Response | HTTP::Server::Response::Output | IO::FileDescriptor+ | Int32 | Nil) at ??
0x590b66: *Kemal::CommonExceptionHandler at ??
0x590450: *Kemal::CommonExceptionHandler#call<HTTP::Server::Context>:(Array(IO) | Bool | HTTP::Server::Context | HTTP::Server::Response | HTTP::Server::Response::Output | IO::FileDescriptor+ | Int32 | Nil) at ??
0x58f846: *Kemal::CommonLogHandler at ??
0x58d091: *Kemal::CommonLogHandler#call<HTTP::Server::Context>:HTTP::Server::Context at ??
0x58c9b1: *Kemal::InitHandler at ??
0x58c655: *Kemal::InitHandler#call<HTTP::Server::Context>:(Array(IO) | Bool | HTTP::Server::Context | HTTP::Server::Response | HTTP::Server::Response::Output | IO::FileDescriptor+ | Int32 | Nil) at ??
0x4acd0c: *process_request<HTTP::Request>:HTTP::Client::Response at ??
0x4ad20d: *post<String, HTTP::Headers, String>:HTTP::Client::Response at ??
0x4ad1b3: ~procProc(Nil) at ??
0x4ac71d: *it<String, String, Int32, Int32, &Proc(Nil)>:(Array(Spec::Result) | Nil) at ??
0x4ac518: ~procProc(Nil) at ??
0x520fe7: *Spec::RootContext::describe<String, String, Int32, &Proc(Nil)>:Spec::Context+ at ??
0x4ac457: *describe<Todo:Module, String, Int32, &Proc(Nil)>:Spec::Context+ at ??
0x495cdb: ??? at ??
0x4a4f09: main at ??
0x7f058aedc830: __libc_start_main at ??
0x494739: _start at ??
0x0: ??? at ??


2016-12-17 10:20:02 -0200 500 POST /todos 14.4ms
.......

Finished in 16.69 milliseconds
8 examples, 0 failures, 0 errors, 0 pending
```

My test code:
```crystal
require "./spec_helper"

describe Todo do
  it "shows empty list of todo items" do
    get "/todos"
    response.body.should eq "[]"
  end

  it "creates a new todo item" do
    json_body = {"title": "Buy milk"}
    post("/todos", headers: HTTP::Headers{"Content-Type" => "application/json"}, body: json_body.to_json)
  end
end
```

My /todos code:
```crystal
post "/todos" do |env|
  title = env.params.json["title"].as(String)
  order = env.params.json.fetch("order", nil).as(Nil | Int64)
  todo = Handler.add_todo_item title, order
  env.response.status_code = 201
  repr(todo, base_url(env)).to_json
end
```

I have no idea what `Exception: Missing hash key: HTTP::Headers::Key(@name="host") (KeyError)` means. :(

**Comment by sdogruyol** [comment]
This is weird.

Crystal expects host key to be present in http  headers.

Can you add host key to http headers?

On Dec 17, 2016 16:24, "Mauricio de Abreu Antunes" <notifications@github.com>
wrote:

I am using this cool library to test my routes. But I am facing this
problem:

2016-12-17 10:20:02 -0200 200 GET /todos 79.6µs
.Exception: Missing hash key: HTTP::Headers::Key(@name="host") (KeyError)
0x4b0777: *CallStack::unwind:Array(Pointer(Void)) at ??
0x4b070a: *CallStack#initialize:Array(Pointer(Void)) at ??
0x4b06da: *CallStack::new:CallStack at ??
0x4a601e: *raise<KeyError>:NoReturn at ??
0x53f14f: *Hash(HTTP::Headers::Key, Array(String)) at ??
0x53dc32: *HTTP::Headers#fetch<HTTP::Headers::Key>:String at ??
0x53dbdd: *HTTP::Headers#[]<String>:String at ??
0x4a99cb: *base_url<HTTP::Server::Context>:String at ??
0x4aa299: ~procProc(HTTP::Server::Context, String) at ??
0x4a95ef: ~proc3Proc(HTTP::Server::Context, String) at ??
0x593376: *Kemal::RouteHandler#process_request<HTTP::Server::Context>:HTTP::Server::Context
at ??
0x5932e6: *Kemal::RouteHandler#call<HTTP::Server::Context>:HTTP::Server::Context
at ??
0x588ea1: *Kemal::FilterHandler at ??
0x588cba: *Kemal::FilterHandler#call<HTTP::Server::Context>:(Array(IO)
| Bool | HTTP::Server::Context | HTTP::Server::Response |
HTTP::Server::Response::Output | IO::FileDescriptor+ | Int32 | Nil) at
??
0x592372: *Kemal::StaticFileHandler at ??
0x591435: *Kemal::StaticFileHandler#call<HTTP::Server::Context>:(Array(IO)
| Bool | HTTP::Server::Context | HTTP::Server::Response |
HTTP::Server::Response::Output | IO::FileDescriptor+ | Int32 | Nil) at
??
0x590b66: *Kemal::CommonExceptionHandler at ??
0x590450: *Kemal::CommonExceptionHandler#call<HTTP::Server::Context>:(Array(IO)
| Bool | HTTP::Server::Context | HTTP::Server::Response |
HTTP::Server::Response::Output | IO::FileDescriptor+ | Int32 | Nil) at
??
0x58f846: *Kemal::CommonLogHandler at ??
0x58d091: *Kemal::CommonLogHandler#call<HTTP::Server::Context>:HTTP::Server::Context
at ??
0x58c9b1: *Kemal::InitHandler at ??
0x58c655: *Kemal::InitHandler#call<HTTP::Server::Context>:(Array(IO) |
Bool | HTTP::Server::Context | HTTP::Server::Response |
HTTP::Server::Response::Output | IO::FileDescriptor+ | Int32 | Nil) at
??
0x4acd0c: *process_request<HTTP::Request>:HTTP::Client::Response at ??
0x4ad20d: *post<String, HTTP::Headers, String>:HTTP::Client::Response at ??
0x4ad1b3: ~procProc(Nil) at ??
0x4ac71d: *it<String, String, Int32, Int32,
&Proc(Nil)>:(Array(Spec::Result) | Nil) at ??
0x4ac518: ~procProc(Nil) at ??
0x520fe7: *Spec::RootContext::describe<String, String, Int32,
&Proc(Nil)>:Spec::Context+ at ??
0x4ac457: *describe<Todo:Module, String, Int32, &Proc(Nil)>:Spec::Context+ at ??
0x495cdb: ??? at ??
0x4a4f09: main at ??
0x7f058aedc830: __libc_start_main at ??
0x494739: _start at ??
0x0: ??? at ??


2016-12-17 10:20:02 -0200 500 POST /todos 14.4ms
.......

Finished in 16.69 milliseconds
8 examples, 0 failures, 0 errors, 0 pending

My test code:

require "./spec_helper"

describe Todo do
  it "shows empty list of todo items" do
    get "/todos"
    response.body.should eq "[]"
  end

  it "creates a new todo item" do
    json_body = {"title": "Buy milk"}
    post("/todos", headers: HTTP::Headers{"Content-Type" =>
"application/json"}, body: json_body.to_json)
  endend

My /todos code:

post "/todos" do |env|
  title = env.params.json["title"].as(String)
  order = env.params.json.fetch("order", nil).as(Nil | Int64)
  todo = Handler.add_todo_item title, order
  env.response.status_code = 201
  repr(todo, base_url(env)).to_jsonend

I have no idea what Exception: Missing hash key:
HTTP::Headers::Key(@name="host")
(KeyError) means. :(

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kemalcr/spec-kemal/issues/8>, or mute the thread

**Comment by mauricioabreu** [comment]
@sdogruyol You are right!

Actually it is a problem in my application.
I have a code that returns the URL for the Todo Item (ReST API). So I need the host in this function:

```crystal
def base_url(env)
  # Set base url like this because Kemal does not
  # support URI parse like Sinatra does.
  # See: https://github.com/sdogruyol/kemal/issues/148
  "http://" + env.request.headers["host"]
end
```

So I can set the base URL for the records.

It is not a Kemal/Spec-Kemal bug but a bad code in my application. Sorry and thank you!

**Comment by sdogruyol** [comment]
Cheers :)
